# Generated by Django 4.2.16 on 2024-11-26 16:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITSpecialist",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("salary", models.PositiveIntegerField(default=500)),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        default="Junior",
                        max_length=10,
                    ),
                ),
                ("level", models.CharField(default="не определено", max_length=50)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
